App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name = 'App_Blog'

# app_name = 'App_Blog'

urlpatterns = [
    # path('', views.BlogList.as_view(), name='blog_list'),
    path('',views.blog_list,name='blog_list'),
    path('write/',views.CreateBlog.as_view(),name='create_blog'),
    path('details/<slug:slug>',views.blog_details,name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/',views.MyBlogs.as_view(),name='my_blogs'),
    path('edit/<pk>',views.UpdateBlog.as_view(),name='edit_blog'),
    path('search/', views.search_blog, name='blog_search'),
    path('total_blog/', views.listish, name='list'),




]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('sign_up/',views.sign_up,name='sign_up'),
    path('login/',views.login_page,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('change-profile/',views.user_change,name='user_change'),
    path('password/',views.pass_change,name='pass_change'),
    path('add-picture/',views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic'),
    path('forgot-password/', views.password_change, name='forgot_password'),


]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
    path('',views.index,name='index'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user=models.OneToOneField(User,related_name='user_profile',on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='profile_pics')









class Employee(models.Model):
    name=models.CharField(max_length=230,default="true")
    dept=models.CharField(max_length=10)
    ph=models.CharField(max_length=10,default="+880")

    def __str__(self) -> str:
        return self.name

        # def __str__(self):
        #     return self.name

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm ,UserChangeForm,SetPasswordForm
from django.contrib.auth.models import User
from App_Login.models import *

class SignUpForm(UserCreationForm):
    email=forms.EmailField(label="email",required=True)
    class Meta:
        model=User
        fields = ('username','email','password1','password2')







class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password')

class ProfilePic(forms.ModelForm):
    class Meta:
        model=UserProfile
        fields= ['profile_pic']

class SetPasswordForm(SetPasswordForm):
    class Meta:
        model = User
        fields = ['new_password1', 'new_password2']

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm,SetPasswordForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm,UserProfileChange,ProfilePic

# Create your views here.
def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)

        if form.is_valid():
            form.save()
            registered = True


    dict = {'form':form,'registered':registered}

    return render(request,'App_Login/sign_up.html',context=dict)






def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
    return render(request, 'App_Login/login.html', context={'form':form})







@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required

def profile(request):
    return render(request,'App_Login/profile.html',context={})


@login_required

def user_change(request):
    current_user=request.user
    form=UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST,instance=current_user) # value replace kore value update korbe

        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user) #updated value reload korbe
    return render(request,'App_Login/change_profile.html',context={'form':form})

@login_required

def pass_change(request):
    current_user=request.user
    changed =False
    form=PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user,data=request.POST)
        if form.is_valid():
            form.save()
            changed = True

    return render(request,'App_Login/change_pass.html',context={'form':form,'changed':changed})

@login_required

@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form=ProfilePic(request.POST,request.FILES)

        if form.is_valid():
            user_obj=form.save(commit=False)
            user_obj.user=request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))

    return render(request, 'App_Login/pro_pic_add.html', context={'form':form})

@login_required

def change_pro_pic(request):
    form= ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST,request.FILES,instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))


    return render(request,'App_Login/pro_pic_add.html',context={'form':form})
@login_required
def password_change(request):
    user = request.user
    form = SetPasswordForm(user)
    return render(request, 'App_Login/Reset_pass.html', {'form': form})

templates/App_Login/Reset_pass.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Creat New Account{% endblock %}
{% block body_block %}

<div class="content-section">
    <h2>Password Reset Confirm</h2>
    <hr>
    <p>Please enter your new password.</p>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-outline-info" type="submit">Reset password</button>
    </form>
</div>


{% endblock %}

templates/App_Login/change_pass.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Pass{% endblock %}
{% block body_block %}
{% if chnaged %}
<div class="alert alert-success">
  Password Changed Successfully!
</div>
{% endif %}
<form method="POST">
{{form|crispy}}
{% csrf_token %}
<button type="submit" name="button" class="btn btn-warning btn-sm">Change</button>
</form>
{% endblock %}

templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Profile {% endblock %}
{% block body_block %}
<form method="POST">
{{form|crispy}}
{% csrf_token %}
<button type="submit" name="button" class="btn btn-warning btn-sm">Change</button>
</form>
{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block body_block %}
<h2>Login:</h2>
<form method="POST">
{{form|crispy}}

{% csrf_token %}
<button type="submit" class="btn btn-primary btn-sm">Login</button>

  <p>Please Sign Up Here <a href="{% url 'App_Login:sign_up' %}">SignUp</a> </p>
</form>
{% endblock %}

templates/App_Login/pro_pic_add.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} Add Pro Pic {% endblock %}
{% block body_block %}
<h2>Profile Add</h2>
<form  method="POST" enctype="multipart/form-data">
{{form|crispy}}
{% csrf_token %}
<button type="submit" class="btn btn-success btn-sm">Update</button>
</form>
{% endblock %}

templates/App_Login/profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} Profile {% endblock %}
{% block body_block %}
<h2>Your Profile</h2>
<br>
{% if user.user_profile %}
<img src='/media/{{user.user_profile.profile_pic}}' class="rounded-circle" width="150px" alt="">
<br>
<br>
<a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Image</a>
{% else %}
<img src='/media/profile_pics/men.png' class="rounded-circle" width="150px" alt="">
<br>
<br>
<a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-info btn-sm">Change Image</a>
{% endif %}
<br>
<p>Username:{{user.username}}</p>
<p>Name:{{user.first_name}} {{user.last_name}} </p>
<p>Email:{{user.email}}</p>
<a href="{% url 'App_Login:user_change' %}" class="btn btn-warning btn-sm">Change Profile Info</a>
{% endblock %}
<br>

templates/App_Login/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Creat New Account{% endblock %}
{% block body_block %}

{% if registered %}
<div class="alert alert-success">
    <p>Accuont Create Successfully <a href="{% url 'App_Login:login' %}">Login Here </a></p>
</div>


{% else %}



<h2>Create New Account</h2>
<form  method="POST">
{{form |crispy}}

{% csrf_token %}
<button type="submit" class="btn btn-success btn-sm" >Create Account</button>
</form>

<br>

<p>Already have an Account?<a href="{% url 'App_Login:login' %}">Login Here</a> </p>


{% endif %}



{% endblock %}