App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name = 'App_Blog'

# app_name = 'App_Blog'

urlpatterns = [
    # path('', views.BlogList.as_view(), name='blog_list'),
    path('',views.blog_list,name='blog_list'),
    path('write/',views.CreateBlog.as_view(),name='create_blog'),
    path('details/<slug:slug>',views.blog_details,name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/',views.MyBlogs.as_view(),name='my_blogs'),
    path('edit/<pk>',views.UpdateBlog.as_view(),name='edit_blog'),
    path('search/', views.search_blog, name='blog_search'),
    path('total_blog/', views.listish, name='list'),




]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('blog/',include('App_Blog.urls')),
    path('',views.index,name='index'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User
from App_Login.models import *

# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Put a Title")
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name="What is on your mind?")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name="Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date',]

    def __str__(self):
        return self.blog_title







class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-comment_date',)

    def __str__(self):
        return self.comment

class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name="liked_blog")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="liker_user")


    def __str__(self):
        return self.user + " likes " + self.blog





class vaccation(models.Model):
    team_mate=models.ForeignKey(Employee,on_delete=models.CASCADE,related_name='cutiya')
    issue_name=models.CharField(max_length=400,default="true")
    publish_date = models.DateTimeField(auto_now_add=True)
    holiday_from=models.DateField()
    holiday_to=models.DateField()

    # def __str__(self) -> str:
    #     return str('team_mate')

    def __str__(self):
        return str(self.team_mate)

App_Blog/forms.py
from django import forms
from App_Blog.models import Blog,Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=('comment',)

App_Blog/views.py
from django.shortcuts import render, HttpResponseRedirect,HttpResponse
from django.views.generic import CreateView, UpdateView, ListView, DetailView, View, TemplateView, DeleteView
from App_Blog.models import Blog, Comment, Likes
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from App_Blog.forms import CommentForm
from django.core.paginator import Paginator
from django.db.models import Count, F
from datetime import datetime
import uuid
# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template.loader import render_to_string

# def print_friendly_blog(request, slug):
#     blog = get_object_or_404(Blog, slug=slug)
#     context = {'blog': blog}
#     html_content = render_to_string('App_Blog/print_friendly_blog.html', context)

#     response = HttpResponse(content_type='application/pdf')
#     response['Content-Disposition'] = f'filename="{blog.slug}.pdf"'

#     pdfkit.from_string(html_content, False, options={'encoding': 'UTF-8'}, output_path=response)

#     return response


class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'App_Blog/create_blog.html'
    fields = ('blog_title', 'blog_content', 'blog_image',)

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ", "-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))

# class BlogList(ListView):
#     context_object_name = 'blogs'
#     model = Blog
#     template_name = 'App_Blog/blog_list.html'
def blog_list(request):
    blogs = Blog.objects.all()
    paginator = Paginator(blogs, 5)  # Display 5 blogs per page

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    recent_posts = Blog.objects.order_by('-publish_date')[:5]

    return render(request, 'App_Blog/blog_list.html', {'page_obj': page_obj,'recent_posts':recent_posts})



@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    already_liked = Likes.objects.filter(blog=blog, user= request.user)
    if already_liked:
        liked = True
    else:
        liked = False
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':slug}))
    return render(request, 'App_Blog/blog_details.html', context={'blog':blog, 'comment_form':comment_form, 'liked':liked,})

@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user
    if not already_liked:
        liked_post = Likes(blog=blog, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))

@login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))

class MyBlogs(LoginRequiredMixin, TemplateView):
    template_name = 'App_Blog/my_blogs.html'


class UpdateBlog(LoginRequiredMixin,UpdateView):
    model=Blog
    fields=('blog_title','blog_content','blog_image')
    template_name='App_Blog/edit_blog.html'

    def get_success_url(self,**kwargs):
        return reverse_lazy('App_Blog:blog_details',kwargs={'slug':self.object.slug})




def search_blog(request):
    query = request.GET.get('q')

    if query:
        blogs = Blog.objects.filter(blog_title__icontains=query)
    else:
        blogs = Blog.objects.all()

    return render(request, 'App_Blog/blog_list.html', {'blogs': blogs})


def listish(request):
    blogs = Blog.objects.all()
    paginator = Paginator(blogs, 5)  # Display 5 blogs per page

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'App_Blog/blog_list.html', {'page_obj': page_obj})

templates/App_Blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block body_block %}
<div class="row">
  <div class="col-sm-6">
    <h2>{{blog.blog_title}}</h2>
    <h4>Posted By: @{{blog.author}}</h4>
    <i><h6>Published On: {{blog.publish_date}}</h6></i>
    <i><h6>Updated On: {{blog.update_date}}</h6></i>
    <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count}} Comments</h6>
  </div>
  <div class="col-sm-6">
    <img src="/media/{{blog.blog_image}}" width="100%">
  </div>

  <p>
    {{blog.blog_content|linebreaks}}
  </p>
  <hr>

  </div>
  {% if not liked %}
  <a href="{% url 'App_Blog:liked_post' pk=blog.pk %}">
    <i class="fa fa-thumbs-o-up fa-2x" aria-hidden="true"></i>
  </a>
  {% else %}
  <a href="{% url 'App_Blog:unliked_post' pk=blog.pk %}">
    <i class="fa fa-thumbs-o-down fa-2x" aria-hidden="true"></i>
  </a>
  {% endif %}
  <div class="row">
    <div class="col-sm-6">
      <hr>
      <h5>Comments:</h5>
      {% for comment in blog.blog_comment.all %}
      <p><a href="#">@{{comment.user}}</a> {{comment.comment}}<br><h6>{{comment.comment_date}}</h6>
      </p>
      {% endfor %}
    </div>
    <div class="col-sm-6">
      <form method="POST">
        {{ comment_form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Comment</button>
      </form>
    </div>

  </div>
  <br>
  <br>

  {% endblock %}

templates/App_Blog/blog_list.html
{% extends 'base.html' %}

{% load custom_filters %}

{% block title_block %} Home {% endblock %}

{% block body_block %}
{% for blog in page_obj %}
<h3>{{blog.blog_title}}</h3>
<h6><i>{{blog.publish_date}}</i></h6>
<div class="row">
  <div class="col-sm-4">
    <img src="{{blog.blog_image.url}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
    <p>{{ post.blog_content|truncatewords:30 }}</p>
    <p>{{ blog.blog_content|range_filter|linebreaks }} 
      <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}" class="btn btn-info btn-sm">Read More</a>
      <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}" target="_blank" class="btn btn-primary btn-sm">Share on Facebook</a>
      <a href="https://twitter.com/intent/tweet?url={{ request.build_absolute_uri }}&text={{ blog.blog_title }}" target="_blank" class="btn btn-info btn-sm">Share on Twitter</a>
    </p>
  </div>
  <div class="col-sm-8">
    <p>{{blog.blog_content|range_filter|linebreaks}} <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">
    <button type="button" name="button" class="btn btn-info btn-sm">Read More</button>  </a></p>
    <h6>Posted By: <a href="#">@{{blog.author}}</a></h6>
    <h6>{{blog.liked_blog.count}} Likes | {{blog.blog_comment.count }} Comments </h6>
  </div>
  


</div>
<hr>
{% endfor %}

<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
      <a href="?page=1">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current-page">{{ page_obj.number }}</span>

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>





{% endblock %}

templates/App_Blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {% endblock %}
{% block body_block %}
<h2>Write Your Blog Here:</h2>
<form method="POST" enctype="multipart/form-data">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-info btn-sm">Publish</button>
</form>
{% endblock %}

templates/App_Blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{blog.blog_title}} {% endblock %}
{% block body_block %}
{% if blog.author == user %}
<form method="POST">
{{form|crispy}}
{% csrf_token %}
<button type="submit" name="button" class="btn btn-primary btn-sm">Update</button>
{% else %}
<p>Your are not allowed to view this page. 404</p>
</form>
{% endif %}
{% endblock %}

templates/App_Blog/list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} Home {% endblock %}
{% block body_block %}
<div class="container">
    <h3>Total Blogs: {{ page_obj.paginator.count }}</h3> <!-- Display the total number of blogs -->
    {% for blog in page_obj %}
    <h3>{{ blog.blog_title }}</h3>
    <!-- Rest of your blog content display -->
    <hr>
    {% endfor %}
    <p>Debug: page_obj={{ page_obj }}</p> <!-- Debug: Print page_obj to see its contents -->
</div>
{% endblock %}

templates/App_Blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title_block %} {{user}} {% endblock %}
{% block body_block %}
{% for blog in user.post_author.all %}
<h3>{{blog.blog_title}}</h3>
<h6>{{blog.publish_date}}</h6>
<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{blog.blog_image}}" width="100%">
  </div>
  <div class="col-sm-8">
    <p>{{blog.blog_content|range_filter|linebreaks}}</p>
    <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}"><button type="button" class="btn btn-info btn-sm" name="button">
      ReadMore
    </button></a>
  </div>
</div>
<button type="button" name="button" class="btn btn-warning btn-sm"><a style="color:white; " href="{% url 'App_Blog:edit_blog' pk=blog.pk %}">Edit</a></button>
<hr>
{% endfor %}
{% endblock %}

templates/App_Blog/print_friendly_blog.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ blog.blog_title }}</title>
    <!-- Include any necessary meta tags, CSS links, or other header content here -->
</head>
<body>
    <h1>{{ blog.blog_title }}</h1>
    <p>{{ blog.blog_content }}</p>
</body>
</html>